version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
    restart: unless-stopped

  cache:
    image: redis:alpine
    restart: unless-stopped
