"""Add Image model for Sprint 3

Revision ID: a163efae8eca
Revises: b2b56351569a
Create Date: 2026-02-03 07:06:31.000408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a163efae8eca'
down_revision: Union[str, None] = 'b2b56351569a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('digest', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('labels_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pulled_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('update_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_image_id'), 'images', ['image_id'], unique=True)
    op.create_index(op.f('ix_images_repository'), 'images', ['repository'], unique=False)
    op.create_index(op.f('ix_images_tag'), 'images', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_tag'), table_name='images')
    op.drop_index(op.f('ix_images_repository'), table_name='images')
    op.drop_index(op.f('ix_images_image_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
